/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#10232f",
        "primary-container": "#263845",
        "on-primary": "#ffffff",
        "on-primary-container": "#8ea1b1",
        "primary-fixed": "#d2e5f6",
        "primary-fixed-dim": "#b6c9d9",
        "on-primary-fixed": "#0a1d2a",
        "on-primary-fixed-variant": "#374956",
        "inverse-primary": "#b6c9d9",

        "secondary": "#964900",
        "secondary-container": "#fd974e",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#6d3300",
        "secondary-fixed": "#ffdcc7",
        "secondary-fixed-dim": "#ffb787",
        "on-secondary-fixed": "#311300",
        "on-secondary-fixed-variant": "#723600",

        "tertiary": "#182227",
        "tertiary-container": "#2e373d",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#96a0a7",
        "tertiary-fixed": "#dae4eb",
        "tertiary-fixed-dim": "#bec8cf",
        "on-tertiary-fixed": "#131d22",
        "on-tertiary-fixed-variant": "#3e484e",

        "surface": "#f5fafa",
        "surface-dim": "#d6dbdb",
        "surface-bright": "#f5fafa",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f5f4",
        "surface-container": "#eaefef",
        "surface-container-high": "#e4e9e9",
        "surface-container-highest": "#dee3e3",
        "surface-variant": "#dee3e3",
        "surface-tint": "#4e616f",
        "on-surface": "#171d1d",
        "on-surface-variant": "#43474b",
        "inverse-surface": "#2c3132",
        "inverse-on-surface": "#edf2f2",

        "outline": "#73777c",
        "outline-variant": "#c3c7cc",
        "background": "#f5fafa",
        "on-background": "#171d1d",

        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",

        // NIRVIK Canonical Brand Palette
        "nirvik-navy": "#263845",
        "nirvik-dark": "#10232f",
        "nirvik-orange": "#FF994F",
        "nirvik-grey": "#BFC9D0",
        "nirvik-light": "#EAEFEF",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        full: "9999px",
      },
      spacing: {
        "stack-tight": "8px",
        "stack-md": "12px",
        "gutter": "16px",
        "panel-padding": "16px",
        "margin-page": "24px",
        "sidebar-width": "240px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "section-heading": ["Inter", "sans-serif"],
        "page-title": ["Inter", "sans-serif"],
        "metadata": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "section-heading": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "page-title": ["26px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "metadata": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-caps": ["10px", { lineHeight: "12px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
